server:
  port: 8080

spring:
  application:
    name: parking-lot-api
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/parking-lot-api-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

