spring:
  application:
    name: parking-lot-app
  datasource:
    url: jdbc:postgresql://db:5432/parking-lot-app-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

