server:
  port: 8080

spring:
  application:
    name: parking-lot-app
  datasource:
    url: jdbc:h2:~/data/parking-lot-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG

